name = "urls-analytics"
main = "src/index.tsx"
compatibility_date = "2023-12-01"


# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "short-urls"
database_id = "ea787ddb-2f20-4f7b-a7d6-65f0d20a8b82"

# [ai]
# binding = "AI"